[project]
name = "SimWorks"
version = "0.6.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "celery>=5.5.3",
    "channels>=4.3.1",
    "channels-redis>=4.3.0",
    "daphne>=4.2.1",
    "django==6.0b1",
    "django-autoslug>=1.9.9",
    # "django-celery-beat>=2.8.1",
    "django-htmx>=1.26.0",
    "django-imagekit>=5.0.0",
    "django-polymorphic>=4.1.0",
    "django-redis>=6.0.0",
    "faker==38.0.0",
    "httpcore>=1.0.9",
    "logfire[django]==4.14.2",
    "openai==2.8.0",
    "opentelemetry-instrumentation-httpx>=0.58b0",
    "pillow>=11.3.0",
    "pre-commit>=4.3.0",
    "psycopg>=3.2.12",
    "psycopg-binary>=3.2.12",
    "pydantic==2.12.3",
    "pydantic-django>=0.1.1",
    "pytest>=8.4.2",
    "pytest-django>=4.11.1",
    "redis>=7.0.0",
    "strawberry-graphql==0.285.0",
    "strawberry-graphql-django==0.67.0",
    "typing-extensions>=4.15.0",
    "zope-interface==8.1.1",
    "python-slugify>=8.0.4",
    "orchestrai",
    "orchestrai-django",
]

[tool.uv.workspace]
members = ["packages/orchestrai", "packages/orchestrai_django"]

[tool.uv.sources]
orchestrai-django = { workspace = true }
orchestrai = { workspace = true }

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
python_files = ["tests/*.py", "tests/**/*.py"]
addopts = "-ra -q"
