[project]
name = "SimWorks"
version = "0.5.21"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "celery>=5.5.2",
    "channels>=4.2.2",
    "channels-redis>=4.2.1",
    "daphne>=4.2.0",
    "django>=5.2.1",
    "django-autoslug>=1.9.9",
    "django-celery-beat>=2.8.1",
    "django-htmx>=1.23.0",
    "django-imagekit>=5.0.0",
    "django-polymorphic>=4.1.0",
    "django-redis>=5.4.0",
    "faker>=37.3.0",
    "strawberry-graphql-django==0.67.0",
    "httpcore>=1.0.9",
    "logfire[django]>=3.24.0",
    "openai>=1.82.0",
    "opentelemetry-instrumentation-httpx>=0.55b1",
    "pillow>=11.2.1",
    "pre-commit>=4.2.0",
    "psycopg>=3.2.9",
    "psycopg-binary>=3.2.9",
    "pydantic>=2.11.5",
    "pydantic-django>=0.1.1",
    "pytest>=8.3.5",
    "redis>=6.1.0",
    "typing-extensions>=4.13.2",
    "zope-interface>=7.2",
    "strawberry-graphql==0.287.0",
]
