name: Docker Image CI

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Log in to the Container registry
      uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push default Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/Dockerfile.prod
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Attest default image
      uses: actions/attest-build-provenance@v3
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true

    - name: Build and push web image
      id: push-web
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/Dockerfile.prod
        target: web
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:web-${{ github.ref_name }}
          ghcr.io/${{ github.repository }}:web-latest
        labels: ${{ steps.meta.outputs.labels }}

    - name: Attest web image
      uses: actions/attest-build-provenance@v3
      with:
        subject-name: ghcr.io/${{ github.repository }}:web-${{ github.ref_name }}
        subject-digest: ${{ steps.push-web.outputs.digest }}
        push-to-registry: true

    - name: Build and push celery image
      id: push-celery
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/Dockerfile.prod
        target: celery
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:celery-${{ github.ref_name }}
          ghcr.io/${{ github.repository }}:celery-latest
        labels: ${{ steps.meta.outputs.labels }}

    - name: Attest celery image
      uses: actions/attest-build-provenance@v3
      with:
        subject-name: ghcr.io/${{ github.repository }}:celery-${{ github.ref_name }}
        subject-digest: ${{ steps.push-celery.outputs.digest }}
        push-to-registry: true

    - name: Build and push beat image
      id: push-beat
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/Dockerfile.prod
        target: beat
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:beat-${{ github.ref_name }}
          ghcr.io/${{ github.repository }}:beat-latest
        labels: ${{ steps.meta.outputs.labels }}

    - name: Attest beat image
      uses: actions/attest-build-provenance@v3
      with:
        subject-name: ghcr.io/${{ github.repository }}:beat-${{ github.ref_name }}
        subject-digest: ${{ steps.push-beat.outputs.digest }}
        push-to-registry: true
